-- noinspection SqlNoDataSourceInspectionForFile

INSERT INTO USER_DETAILS(ID, NAME, BIRTH_DATE)
VALUES (1, 'Jeeva', '1990-04-12');

INSERT INTO USER_DETAILS(ID, NAME, BIRTH_DATE)
VALUES (2, 'Gokul', '1991-04-12');

INSERT INTO USER_DETAILS(ID, NAME, BIRTH_DATE)
VALUES (3, 'DurgaPrasad', '1992-04-12');

INSERT INTO USER_DETAILS(ID, NAME, BIRTH_DATE)
VALUES (4, 'Naveen', '1993-04-12');

INSERT INTO USER_DETAILS(ID, NAME, BIRTH_DATE)
VALUES (5, 'Lokesh', '1994-04-12');

INSERT INTO USER_DETAILS(ID, NAME, BIRTH_DATE)
VALUES (6, 'Roshini', '1994-04-12');

